

process.on('uncaughtException', function (exception) {
    console.log(exception);
});